# Generated by Django 5.2.14 on 2026-06-03 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('provider_type', models.CharField(choices=[('sip', 'SIP'), ('iax2', 'IAX2'), ('other', 'Other')], default='sip', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('prompt_name', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivrs', to='core.location')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Extension numbers must be exactly four digits.', regex='^\\d{4}$')])),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sip_username', models.CharField(blank=True, max_length=80)),
                ('voicemail_enabled', models.BooleanField(default=True)),
                ('emergency_calling_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core.location')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('strategy', models.CharField(choices=[('ring_all', 'Ring all'), ('least_recent', 'Least recent'), ('fewest_calls', 'Fewest calls'), ('round_robin', 'Round robin')], default='ring_all', max_length=24)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('retry_seconds', models.PositiveSmallIntegerField(default=5)),
                ('music_on_hold', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='core.location')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OutboundRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('dial_pattern', models.CharField(max_length=80)),
                ('priority', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_emergency_route', models.BooleanField(default=False)),
                ('caller_id_number', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_routes', to='core.location')),
            ],
            options={
                'ordering': ['location', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PagingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('page_code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Extension numbers must be exactly four digits.', regex='^\\d{4}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paging_groups', to='core.location')),
            ],
            options={
                'ordering': ['page_code'],
            },
        ),
        migrations.CreateModel(
            name='PagingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paging_group_memberships', to='core.extension')),
                ('paging_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.paginggroup')),
            ],
            options={
                'ordering': ['paging_group', 'extension'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='MAC addresses must be 12 uppercase hexadecimal characters.', regex='^[0-9A-F]{12}$')])),
                ('model', models.CharField(choices=[('CP-9971', 'Cisco CP-9971'), ('CP-9951', 'Cisco CP-9951'), ('CP-8961', 'Cisco CP-8961'), ('other', 'Other')], default='CP-9971', max_length=24)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.location')),
            ],
            options={
                'ordering': ['mac_address'],
            },
        ),
        migrations.CreateModel(
            name='PhoneLineAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(blank=True, max_length=120)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_appearances', to='core.extension')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_appearances', to='core.phone')),
            ],
            options={
                'ordering': ['phone', 'line_index'],
            },
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penalty', models.PositiveSmallIntegerField(default=0)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_memberships', to='core.extension')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.callqueue')),
            ],
            options={
                'ordering': ['queue', 'penalty', 'extension'],
            },
        ),
        migrations.CreateModel(
            name='RingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('strategy', models.CharField(choices=[('ring_all', 'Ring all'), ('hunt', 'Hunt')], default='ring_all', max_length=16)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ring_groups', to='core.location')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InboundDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('destination_type', models.CharField(choices=[('extension', 'Extension'), ('ivr', 'IVR'), ('ring_group', 'Ring group'), ('queue', 'Queue')], max_length=24)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_destinations', to='core.extension')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_destinations', to='core.callqueue')),
                ('ivr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_destinations', to='core.ivr')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_destinations', to='core.location')),
                ('ring_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_destinations', to='core.ringgroup')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ring_group_memberships', to='core.extension')),
                ('ring_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.ringgroup')),
            ],
            options={
                'ordering': ['ring_group', 'priority', 'extension'],
            },
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('trunk_type', models.CharField(choices=[('sip', 'SIP'), ('iax2', 'IAX2')], default='sip', max_length=16)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('is_emergency_capable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trunks', to='core.location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trunks', to='core.provider')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OutboundRouteTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('outbound_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_trunks', to='core.outboundroute')),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_route_links', to='core.trunk')),
            ],
            options={
                'ordering': ['outbound_route', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="DIDs must be 7 to 15 digits, optionally prefixed with '+'.", regex='^\\+?[1-9]\\d{6,14}$')])),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('direct_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_dids', to='core.extension')),
                ('default_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dids', to='core.inbounddestination')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dids', to='core.location')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dids', to='core.provider')),
                ('trunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dids', to='core.trunk')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='IVRMenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digit', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='IVR menu digits must be 0-9.', regex='^[0-9]$')])),
                ('label', models.CharField(blank=True, max_length=120)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ivr_menu_options', to='core.inbounddestination')),
                ('ivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_options', to='core.ivr')),
            ],
            options={
                'ordering': ['ivr', 'digit'],
                'constraints': [models.UniqueConstraint(fields=('ivr', 'digit'), name='unique_ivr_digit'), models.CheckConstraint(condition=models.Q(('digit__regex', '^[0-9]$')), name='ivr_menu_option_digit')],
            },
        ),
        migrations.AddConstraint(
            model_name='ivr',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_ivr_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^\\d{4}$')), name='extension_number_four_digits'),
        ),
        migrations.AddConstraint(
            model_name='callqueue',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_queue_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='outboundroute',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_outbound_route_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='outboundroute',
            constraint=models.UniqueConstraint(fields=('location', 'priority'), name='unique_outbound_route_priority_per_location'),
        ),
        migrations.AddConstraint(
            model_name='paginggroup',
            constraint=models.CheckConstraint(condition=models.Q(('page_code__regex', '^\\d{4}$')), name='paging_group_page_code_four_digits'),
        ),
        migrations.AddConstraint(
            model_name='paginggroup',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_paging_group_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='paginggroupmember',
            constraint=models.UniqueConstraint(fields=('paging_group', 'extension'), name='unique_paging_group_member'),
        ),
        migrations.AddConstraint(
            model_name='phone',
            constraint=models.CheckConstraint(condition=models.Q(('mac_address__regex', '^[0-9A-F]{12}$')), name='phone_mac_upper_hex_12'),
        ),
        migrations.AddConstraint(
            model_name='phonelineappearance',
            constraint=models.UniqueConstraint(fields=('phone', 'line_index'), name='unique_phone_line_index'),
        ),
        migrations.AddConstraint(
            model_name='phonelineappearance',
            constraint=models.UniqueConstraint(fields=('phone', 'extension'), name='unique_phone_extension_appearance'),
        ),
        migrations.AddConstraint(
            model_name='queuemember',
            constraint=models.UniqueConstraint(fields=('queue', 'extension'), name='unique_queue_member'),
        ),
        migrations.AddConstraint(
            model_name='ringgroup',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_ring_group_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='inbounddestination',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_inbound_destination_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='inbounddestination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_type', 'extension'), ('extension__isnull', False), ('ivr__isnull', True), ('queue__isnull', True), ('ring_group__isnull', True)), models.Q(('destination_type', 'ivr'), ('extension__isnull', True), ('ivr__isnull', False), ('queue__isnull', True), ('ring_group__isnull', True)), models.Q(('destination_type', 'ring_group'), ('extension__isnull', True), ('ivr__isnull', True), ('queue__isnull', True), ('ring_group__isnull', False)), models.Q(('destination_type', 'queue'), ('extension__isnull', True), ('ivr__isnull', True), ('queue__isnull', False), ('ring_group__isnull', True)), _connector='OR'), name='inbound_destination_single_matching_target'),
        ),
        migrations.AddConstraint(
            model_name='ringgroupmember',
            constraint=models.UniqueConstraint(fields=('ring_group', 'extension'), name='unique_ring_group_member'),
        ),
        migrations.AddConstraint(
            model_name='trunk',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_trunk_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='outboundroutetrunk',
            constraint=models.UniqueConstraint(fields=('outbound_route', 'trunk'), name='unique_outbound_route_trunk'),
        ),
        migrations.AddConstraint(
            model_name='outboundroutetrunk',
            constraint=models.UniqueConstraint(fields=('outbound_route', 'priority'), name='unique_outbound_route_trunk_priority'),
        ),
        migrations.AddConstraint(
            model_name='did',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^\\+?[1-9]\\d{6,14}$')), name='did_number_e164ish'),
        ),
    ]
