# Generated by Django 5.2.14 on 2026-06-03 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_portaluserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='caller_id_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='extension',
            name='caller_id_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='extension',
            name='recording_policy',
            field=models.CharField(choices=[('inherit', 'Inherit'), ('never', 'Never'), ('on_demand', 'On demand'), ('always', 'Always')], default='inherit', max_length=16),
        ),
        migrations.AddField(
            model_name='extension',
            name='sip_password',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='extension',
            name='voicemail_pin',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Voicemail PINs must be 4 to 16 digits.', regex='^\\d{4,16}$')]),
        ),
    ]
