# Generated by Codex for APR-59 on 2026-06-03

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog_portaluserprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="agent_secret",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="agent secret"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="ami_host",
            field=models.CharField(default="", max_length=255, verbose_name="AMI host"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="ami_port",
            field=models.PositiveIntegerField(
                default=5038,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="AMI port",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="ami_secret",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="AMI secret"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="ami_username",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="AMI username"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="default_did",
            field=models.CharField(
                default="",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="DIDs must be 7 to 15 digits, optionally prefixed with '+'.",
                        regex="^\\+?[1-9]\\d{6,14}$",
                    )
                ],
                verbose_name="default DID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="deployment_ssh_host",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="deployment SSH host"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="deployment_ssh_known_hosts",
            field=models.TextField(blank=True, default="", verbose_name="deployment SSH known hosts"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="deployment_ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="deployment SSH port",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="deployment_ssh_private_key",
            field=models.TextField(blank=True, default="", verbose_name="deployment SSH private key"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="deployment_ssh_username",
            field=models.CharField(blank=True, default="", max_length=80, verbose_name="deployment SSH username"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("not_deployed", "Not deployed"),
                    ("ready", "Ready"),
                    ("deployed", "Deployed"),
                    ("failed", "Failed"),
                ],
                default="not_deployed",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="emergency_caller_id",
            field=models.CharField(
                default="",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="DIDs must be 7 to 15 digits, optionally prefixed with '+'.",
                        regex="^\\+?[1-9]\\d{6,14}$",
                    )
                ],
                verbose_name="emergency caller ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="emergency_trunk",
            field=models.CharField(default="", max_length=120, verbose_name="emergency trunk"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="iax_bind_ip",
            field=models.CharField(
                default="",
                max_length=39,
                validators=[core.models.ip_address_validator],
                verbose_name="IAX bind IP",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="iax_port",
            field=models.PositiveIntegerField(
                default=4569,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="IAX port",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="lan_subnet",
            field=models.CharField(
                default="",
                max_length=43,
                validators=[core.models.cidr_network_validator],
                verbose_name="LAN subnet",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="last_deployed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last deployed"),
        ),
        migrations.AddField(
            model_name="location",
            name="pbx_lan_ip",
            field=models.CharField(
                default="",
                max_length=39,
                validators=[core.models.ip_address_validator],
                verbose_name="PBX LAN IP",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="pbx_warp_ip",
            field=models.CharField(
                default="",
                max_length=39,
                validators=[core.models.ip_address_validator],
                verbose_name="PBX WARP IP",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="recording_retention_days",
            field=models.PositiveIntegerField(
                default=365,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="recording retention days",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="rtp_port_end",
            field=models.PositiveIntegerField(
                default=20000,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="RTP port end",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="rtp_port_start",
            field=models.PositiveIntegerField(
                default=10000,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="RTP port start",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="sip_bind_ip",
            field=models.CharField(
                default="",
                max_length=39,
                validators=[core.models.ip_address_validator],
                verbose_name="SIP bind IP",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="sip_port",
            field=models.PositiveIntegerField(
                default=5060,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="SIP port",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_from_email",
            field=models.EmailField(default="", max_length=254, verbose_name="SMTP from email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_host",
            field=models.CharField(default="", max_length=255, verbose_name="SMTP host"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_password",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="SMTP password"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_port",
            field=models.PositiveIntegerField(
                default=587,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name="SMTP port",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False, verbose_name="SMTP use SSL"),
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_use_tls",
            field=models.BooleanField(default=True, verbose_name="SMTP use TLS"),
        ),
        migrations.AddField(
            model_name="location",
            name="smtp_username",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="SMTP username"),
            preserve_default=False,
        ),
    ]
