# Generated by Codex for APR-60 on 2026-06-03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_location_management_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="caller_id_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="extension",
            name="caller_id_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[core.models.did_number_validator],
            ),
        ),
        migrations.AddField(
            model_name="extension",
            name="recording_policy",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit location policy"),
                    ("always", "Always record"),
                    ("on_demand", "On demand"),
                    ("never", "Never record"),
                ],
                default="inherit",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="extension",
            name="sip_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="extension",
            name="voicemail_pin",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[core.models.voicemail_pin_validator],
            ),
        ),
    ]
