# Generated by Codex for APR-65 on 2026-06-03

import django.core.validators
from django.db import migrations, models


RECORDING_POLICY_CHOICES = [
    ("never", "Off"),
    ("always", "Always record"),
    ("on_demand", "On demand"),
]


def recording_inherit_to_never(apps, schema_editor):
    extension_model = apps.get_model("core", "Extension")
    extension_model.objects.filter(recording_policy="inherit").update(recording_policy="never")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_action_serviceidentity_apikey"),
        ("core", "0004_extension_management_fields"),
    ]

    operations = [
        migrations.RunPython(recording_inherit_to_never, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="location",
            name="recording_retention_days",
            field=models.PositiveIntegerField(
                default=90,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="recording retention days",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="smtp_from_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="SMTP from email"),
        ),
        migrations.AlterField(
            model_name="location",
            name="smtp_host",
            field=models.CharField(blank=True, max_length=255, verbose_name="SMTP host"),
        ),
        migrations.AlterField(
            model_name="extension",
            name="recording_policy",
            field=models.CharField(
                choices=RECORDING_POLICY_CHOICES,
                default="never",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="callqueue",
            name="recording_policy",
            field=models.CharField(
                choices=RECORDING_POLICY_CHOICES,
                default="never",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="outboundroute",
            name="recording_policy",
            field=models.CharField(
                choices=RECORDING_POLICY_CHOICES,
                default="never",
                max_length=16,
            ),
        ),
    ]
