# Generated by Codex for APR-61 on 2026-06-03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_action_serviceidentity_apikey"),
        ("core", "0004_extension_management_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneSpeedDial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("label", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=64)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speed_dials",
                        to="core.phone",
                    ),
                ),
            ],
            options={
                "ordering": ["phone", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("phone", "position"),
                        name="unique_phone_speed_dial_position",
                    ),
                ],
            },
        ),
    ]
