# Generated by Codex for APR-63 on 2026-06-03

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_phone_speed_dials"),
        ("core", "0005_voicemail_recording_retention"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="default_inbound_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_locations",
                to="core.inbounddestination",
                verbose_name="default inbound destination",
            ),
        ),
        migrations.AlterField(
            model_name="did",
            name="default_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dids",
                to="core.inbounddestination",
            ),
        ),
        migrations.AddField(
            model_name="ivr",
            name="timeout_seconds",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="ivr",
            name="business_hours_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_hours_ivrs",
                to="core.inbounddestination",
            ),
        ),
        migrations.AddField(
            model_name="ivr",
            name="after_hours_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="after_hours_ivrs",
                to="core.inbounddestination",
            ),
        ),
        migrations.AddField(
            model_name="ivr",
            name="timeout_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timeout_ivrs",
                to="core.inbounddestination",
            ),
        ),
        migrations.AddField(
            model_name="ivr",
            name="invalid_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invalid_input_ivrs",
                to="core.inbounddestination",
            ),
        ),
        migrations.AddField(
            model_name="callqueue",
            name="overflow_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overflow_queues",
                to="core.inbounddestination",
            ),
        ),
        migrations.CreateModel(
            name="FeatureCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=8, validators=[core.models.feature_code_validator])),
                ("name", models.CharField(max_length=120)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("voicemail_main", "Voicemail main"),
                            ("voicemail_direct", "Direct voicemail"),
                            ("call_pickup", "Call pickup"),
                            ("directed_pickup", "Directed pickup"),
                            ("park", "Call park"),
                            ("paging_prefix", "Paging prefix"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feature_codes",
                        to="core.inbounddestination",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_codes",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location", "code"],
                "constraints": [
                    models.UniqueConstraint(fields=("location", "code"), name="unique_feature_code_per_location"),
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^[0-9*#]{1,8}$")),
                        name="feature_code_dialable",
                    ),
                ],
            },
        ),
    ]
