# Generated by Codex for APR-62 on 2026-06-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_phone_speed_dials"),
        ("core", "0005_voicemail_recording_retention"),
    ]

    operations = []
