# Generated by Codex for APR-62 on 2026-06-03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_0005_phone_speed_dials_0005_voicemail_recording_retention"),
    ]

    operations = [
        migrations.AddField(
            model_name="trunk",
            name="password",
            field=models.CharField(blank=True, max_length=255, verbose_name="password / secret"),
        ),
        migrations.AddField(
            model_name="outboundroute",
            name="caller_id_source",
            field=models.CharField(
                choices=[
                    ("extension_did", "Extension DID"),
                    ("location_default", "Location default DID"),
                    ("emergency", "Emergency caller ID"),
                    ("custom", "Custom caller ID"),
                ],
                default="location_default",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="outboundroute",
            name="caller_id_number",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[core.models.did_number_validator],
            ),
        ),
    ]
