# Generated by Codex for APR-66 on 2026-06-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_inbound_routing_configuration"),
        ("core", "0007_provider_trunk_outbound_route_management"),
    ]

    operations = []
