# Generated by Codex for APR-66 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_inbound_routing_provider_trunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="firmware_load_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
