# Generated by Django 5.2.15 on 2026-06-06 02:23

import django.db.models.deletion
from django.db import migrations, models


def link_existing_emergency_trunks(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    Trunk = apps.get_model('core', 'Trunk')
    for location in Location.objects.exclude(emergency_trunk='').iterator():
        trunk = (
            Trunk.objects.filter(
                location_id=location.id,
                name=location.emergency_trunk,
                is_emergency_capable=True,
            )
            .order_by('id')
            .first()
        )
        if trunk is None:
            continue
        location.emergency_trunk_ref_id = trunk.id
        location.save(update_fields=['emergency_trunk_ref'])


def unlink_existing_emergency_trunks(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    Location.objects.update(emergency_trunk_ref=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_serviceidentity_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='emergency_trunk_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_for_locations', to='core.trunk', verbose_name='emergency trunk record'),
        ),
        migrations.RunPython(link_existing_emergency_trunks, unlink_existing_emergency_trunks),
    ]
