# Generated by Django 5.2.15 on 2026-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_location_emergency_trunk_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="timezone",
            field=models.CharField(default="America/Los_Angeles", max_length=64),
        ),
    ]
