# Generated by Django 5.2.15 on 2026-06-13 00:00

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_location_timezone_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="iax_bind_ip",
            field=models.CharField(
                default="0.0.0.0",
                max_length=39,
                validators=[core.models.ip_address_validator],
                verbose_name="IAX bind IP",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sip_bind_ip",
            field=models.CharField(
                default="0.0.0.0",
                max_length=39,
                validators=[core.models.ip_address_validator],
                verbose_name="SIP bind IP",
            ),
        ),
    ]
