# Generated by Django 5.2.15 on 2026-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_location_listen_address_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="ami_host",
            field=models.CharField(default="0.0.0.0", max_length=255, verbose_name="AMI host"),
        ),
    ]
