# Generated by Django 5.2.15 on 2026-06-13 00:00

from django.db import migrations


DEFAULT_FEATURE_CODES = (
    {
        "code": "*98",
        "name": "Voicemail main",
        "feature_type": "voicemail_main",
        "notes": "Access the shared voicemail menu.",
    },
    {
        "code": "*8",
        "name": "Call pickup",
        "feature_type": "call_pickup",
        "notes": "Pick up a ringing call in the pickup group.",
    },
    {
        "code": "**",
        "name": "Directed pickup",
        "feature_type": "directed_pickup",
        "notes": "Prefix for directed pickup by extension.",
    },
    {
        "code": "700",
        "name": "Call park",
        "feature_type": "park",
        "notes": "Park the current call.",
    },
    {
        "code": "*80",
        "name": "Paging prefix",
        "feature_type": "paging_prefix",
        "notes": "Prefix for paging groups.",
    },
)


def seed_default_feature_codes(apps, schema_editor):
    Location = apps.get_model("core", "Location")
    FeatureCode = apps.get_model("core", "FeatureCode")
    for location in Location.objects.iterator():
        for spec in DEFAULT_FEATURE_CODES:
            FeatureCode.objects.get_or_create(
                location_id=location.id,
                code=spec["code"],
                defaults={
                    "name": spec["name"],
                    "feature_type": spec["feature_type"],
                    "notes": spec["notes"],
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_location_ami_host_default"),
    ]

    operations = [
        migrations.RunPython(seed_default_feature_codes, migrations.RunPython.noop),
    ]
