from __future__ import annotations

from dataclasses import dataclass
from typing import Any


RTP_CONFIG_FILENAME = "rtp.conf"
RTP_PORT_MIN = 1
RTP_PORT_MAX = 65535
DEFAULT_RTP_PORT_START = 10000
DEFAULT_RTP_PORT_END = 20000


@dataclass(frozen=True)
class RTPPortRange:
    start: int
    end: int


class RTPRangeError(ValueError):
    def __init__(self, field_errors: dict[str, str]):
        self.field_errors = field_errors
        super().__init__("Invalid RTP port range.")


def validate_rtp_port_range(start: Any, end: Any) -> RTPPortRange:
    errors: dict[str, str] = {}
    start_port = _coerce_port(start, "rtp_port_start", errors)
    end_port = _coerce_port(end, "rtp_port_end", errors)

    if start_port is not None and end_port is not None and start_port > end_port:
        errors["rtp_port_end"] = "RTP port end must be greater than or equal to RTP port start."

    if errors:
        raise RTPRangeError(errors)

    return RTPPortRange(start=start_port, end=end_port)


def validate_location_rtp_range(location: Any) -> RTPPortRange:
    return validate_rtp_port_range(
        getattr(location, "rtp_port_start", DEFAULT_RTP_PORT_START),
        getattr(location, "rtp_port_end", DEFAULT_RTP_PORT_END),
    )


def render_rtp_conf(location: Any) -> str:
    rtp_range = validate_location_rtp_range(location)
    location_name = getattr(location, "name", "location")
    lines = [
        f"; Generated by PBX Config Portal for {location_name}",
        "; RTP media port range",
        "",
        "[general]",
        f"rtpstart={rtp_range.start}",
        f"rtpend={rtp_range.end}",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _coerce_port(value: Any, field_name: str, errors: dict[str, str]) -> int | None:
    label = {
        "rtp_port_start": "RTP port start",
        "rtp_port_end": "RTP port end",
    }[field_name]

    if value is None or value == "":
        errors[field_name] = f"{label} is required."
        return None

    if isinstance(value, bool) or isinstance(value, float):
        errors[field_name] = f"{label} must be an integer between {RTP_PORT_MIN} and {RTP_PORT_MAX}."
        return None

    try:
        port = int(value)
    except (TypeError, ValueError):
        errors[field_name] = f"{label} must be an integer between {RTP_PORT_MIN} and {RTP_PORT_MAX}."
        return None

    if port < RTP_PORT_MIN or port > RTP_PORT_MAX:
        errors[field_name] = f"{label} must be between {RTP_PORT_MIN} and {RTP_PORT_MAX}."
        return None

    return port
