from types import SimpleNamespace
import unittest

from .ami_credentials import (
    AMI_USERNAME_MAX_LENGTH,
    ami_credentials_audit_payload,
    ensure_location_ami_credentials,
    generate_ami_secret,
    generate_ami_username,
    render_manager_conf,
)


class AMICredentialGenerationTests(unittest.TestCase):
    def test_username_generation_normalizes_location_slug_and_adds_token(self):
        username = generate_ami_username("Branch HQ / West", token_factory=lambda: "ABC123")

        self.assertEqual(username, "ami-branch-hq-west-abc123")
        self.assertLessEqual(len(username), AMI_USERNAME_MAX_LENGTH)

    def test_secret_generation_uses_strong_urlsafe_token(self):
        secret = generate_ami_secret()

        self.assertGreaterEqual(len(secret), 40)
        self.assertNotIn(" ", secret)

    def test_creation_generation_fills_missing_values_without_overwriting_manual_values(self):
        missing = SimpleNamespace(slug="branch-hq", name="Branch HQ", ami_username="", ami_secret="")
        missing_update = ensure_location_ami_credentials(
            missing,
            username_factory=lambda seed: f"ami-{seed}-fixed",
            secret_factory=lambda: "generated-secret",
        )

        self.assertEqual(missing.ami_username, "ami-branch-hq-fixed")
        self.assertEqual(missing.ami_secret, "generated-secret")
        self.assertEqual(missing_update.event, "generated")
        self.assertEqual(missing_update.changed_fields, ["ami_username", "ami_secret"])

        manual = SimpleNamespace(
            slug="branch-hq",
            name="Branch HQ",
            ami_username="manual-user",
            ami_secret="manual-secret",
        )
        manual_update = ensure_location_ami_credentials(
            manual,
            username_factory=lambda seed: "unexpected-user",
            secret_factory=lambda: "unexpected-secret",
        )

        self.assertEqual(manual.ami_username, "manual-user")
        self.assertEqual(manual.ami_secret, "manual-secret")
        self.assertEqual(manual_update.event, "preserved")
        self.assertFalse(manual_update.changed)


class AMICredentialRotationTests(unittest.TestCase):
    def test_rotation_changes_secret_and_redacted_audit_payload_has_no_secret_value(self):
        location = SimpleNamespace(
            slug="branch-hq",
            name="Branch HQ",
            ami_username="manual-user",
            ami_secret="old-secret-value",
        )

        update = ensure_location_ami_credentials(
            location,
            rotate=True,
            username_factory=lambda seed: "ami-branch-hq-rotated",
            secret_factory=lambda: "new-secret-value",
        )
        payload = ami_credentials_audit_payload(update)
        payload_text = repr(payload)

        self.assertEqual(location.ami_username, "ami-branch-hq-rotated")
        self.assertEqual(location.ami_secret, "new-secret-value")
        self.assertNotEqual(location.ami_secret, "old-secret-value")
        self.assertEqual(update.event, "rotated")
        self.assertEqual(update.changed_fields, ["ami_username", "ami_secret"])
        self.assertNotIn("old-secret-value", payload_text)
        self.assertNotIn("new-secret-value", payload_text)
        self.assertTrue(payload["sensitive_value_changed"])


class ManagerConfGoldenTests(unittest.TestCase):
    def test_manager_conf_contains_generated_location_credentials(self):
        location = SimpleNamespace(
            name="Branch HQ",
            slug="branch-hq",
            ami_host="127.0.0.1",
            ami_port=5038,
            ami_username="ami-branch-hq-fixed",
            ami_secret="generated-secret",
        )

        self.assertEqual(
            render_manager_conf(
                location,
                header_lines=[
                    "; Generated by PBX Config Portal for Branch HQ",
                    "; Asterisk Manager Interface",
                    "",
                ],
            ),
            "\n".join(
                [
                    "; Generated by PBX Config Portal for Branch HQ",
                    "; Asterisk Manager Interface",
                    "",
                    "[general]",
                    "enabled=yes",
                    "port=5038",
                    "bindaddr=127.0.0.1",
                    "webenabled=no",
                    "",
                    "[ami-branch-hq-fixed]",
                    "secret=generated-secret",
                    "read=system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan",
                    "write=system,call,agent,user,config,command,reporting,originate",
                    "permit=127.0.0.1/255.255.255.255",
                    "",
                ]
            ),
        )


if __name__ == "__main__":
    unittest.main()
