from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
import unittest

from core.rtp_config import (
    DEFAULT_RTP_PORT_END,
    DEFAULT_RTP_PORT_START,
    RTP_CONFIG_FILENAME,
    RTPPortRange,
    RTPRangeError,
    render_rtp_conf,
    validate_rtp_port_range,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]


class RTPRangeValidationTests(unittest.TestCase):
    def test_accepts_default_and_string_ports(self):
        self.assertEqual(
            validate_rtp_port_range(str(DEFAULT_RTP_PORT_START), str(DEFAULT_RTP_PORT_END)),
            RTPPortRange(start=DEFAULT_RTP_PORT_START, end=DEFAULT_RTP_PORT_END),
        )

    def test_rejects_start_before_asterisk_port_bounds(self):
        with self.assertRaises(RTPRangeError) as context:
            validate_rtp_port_range(0, DEFAULT_RTP_PORT_END)

        self.assertEqual(
            context.exception.field_errors,
            {"rtp_port_start": "RTP port start must be between 1 and 65535."},
        )

    def test_rejects_end_after_asterisk_port_bounds(self):
        with self.assertRaises(RTPRangeError) as context:
            validate_rtp_port_range(DEFAULT_RTP_PORT_START, 65536)

        self.assertEqual(
            context.exception.field_errors,
            {"rtp_port_end": "RTP port end must be between 1 and 65535."},
        )

    def test_rejects_non_integer_ports(self):
        with self.assertRaises(RTPRangeError) as context:
            validate_rtp_port_range("not-a-port", DEFAULT_RTP_PORT_END)

        self.assertEqual(
            context.exception.field_errors,
            {"rtp_port_start": "RTP port start must be an integer between 1 and 65535."},
        )

    def test_rejects_float_ports(self):
        with self.assertRaises(RTPRangeError) as context:
            validate_rtp_port_range(10000.0, DEFAULT_RTP_PORT_END)

        self.assertEqual(
            context.exception.field_errors,
            {"rtp_port_start": "RTP port start must be an integer between 1 and 65535."},
        )

    def test_rejects_reversed_range(self):
        with self.assertRaises(RTPRangeError) as context:
            validate_rtp_port_range(20000, 10000)

        self.assertEqual(
            context.exception.field_errors,
            {"rtp_port_end": "RTP port end must be greater than or equal to RTP port start."},
        )


class RTPConfGoldenTests(unittest.TestCase):
    def test_default_rtp_conf_output(self):
        location = SimpleNamespace(
            name="HQ",
            rtp_port_start=DEFAULT_RTP_PORT_START,
            rtp_port_end=DEFAULT_RTP_PORT_END,
        )

        self.assertEqual(
            render_rtp_conf(location),
            (
                "; Generated by PBX Config Portal for HQ\n"
                "; RTP media port range\n"
                "\n"
                "[general]\n"
                "rtpstart=10000\n"
                "rtpend=20000\n"
            ),
        )

    def test_custom_rtp_conf_output(self):
        location = SimpleNamespace(name="Branch PBX", rtp_port_start=12000, rtp_port_end=12100)

        self.assertEqual(
            render_rtp_conf(location),
            (
                "; Generated by PBX Config Portal for Branch PBX\n"
                "; RTP media port range\n"
                "\n"
                "[general]\n"
                "rtpstart=12000\n"
                "rtpend=12100\n"
            ),
        )


class RTPManifestSourceTests(unittest.TestCase):
    def test_config_export_source_includes_rtp_in_asterisk_manifest_pipeline(self):
        source = (PROJECT_ROOT / "core" / "config_export.py").read_text(encoding="utf-8")

        self.assertIn("RTP_CONFIG_FILENAME", source)
        self.assertIn("RTP_CONFIG_FILENAME: _render_rtp_conf", source)
        self.assertIn("for filename in ASTERISK_CONFIG_FILENAMES", source)
        self.assertIn('f"asterisk/{filename}"', source)

    def test_export_archive_golden_fixtures_include_rtp_conf(self):
        fixture_dir = PROJECT_ROOT / "core" / "testdata" / "export_archive"
        manifest = json.loads((fixture_dir / "manifest.json").read_text(encoding="utf-8"))
        manifest_paths = {file["path"] for file in manifest["files"]}

        self.assertEqual(RTP_CONFIG_FILENAME, "rtp.conf")
        self.assertIn("asterisk/rtp.conf", manifest_paths)
        self.assertIn("  asterisk/rtp.conf", (fixture_dir / "SHA256SUMS").read_text(encoding="utf-8"))
        self.assertIn("asterisk/rtp.conf|", (fixture_dir / "zip-layout.txt").read_text(encoding="utf-8"))
        self.assertIn("asterisk/rtp.conf|", (fixture_dir / "staging-layout.txt").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
