from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("locations/", views.location_list, name="locations"),
    path("locations/new/", views.location_create, name="location-create"),
    path("locations/<slug:slug>/", views.location_detail, name="location-detail"),
    path("locations/<slug:slug>/edit/", views.location_update, name="location-edit"),
    path("locations/<slug:slug>/delete/", views.location_delete, name="location-delete"),
    path("extensions/", views.extension_list, name="extensions"),
    path("extensions/new/", views.extension_create, name="extension-create"),
    path("extensions/import/", views.extension_import, name="extension-import"),
    path("extensions/export/", views.extension_export, name="extension-export"),
    path("extensions/template/", views.extension_template, name="extension-template"),
    path("extensions/<str:number>/edit/", views.extension_update, name="extension-edit"),
    path("extensions/<str:number>/delete/", views.extension_delete, name="extension-delete"),
    path("phones/", views.phone_list, name="phones"),
    path("phones/new/", views.phone_create, name="phone-create"),
    path("phones/export/", views.phone_export, name="phone-export"),
    path("phones/template/", views.phone_template, name="phone-template"),
    path("phones/dids-template/", views.did_template, name="did-template"),
    path("phones/speed-dials/export/", views.speed_dial_export, name="speed-dial-export"),
    path("phones/speed-dials/template/", views.speed_dial_template, name="speed-dial-template"),
    path("phones/<str:mac_address>/edit/", views.phone_update, name="phone-edit"),
    path("phones/<str:mac_address>/delete/", views.phone_delete, name="phone-delete"),
    path("trunks/", views.trunk_list, name="trunks"),
    path("trunks/providers/new/", views.provider_create, name="provider-create"),
    path("trunks/providers/<slug:slug>/edit/", views.provider_update, name="provider-edit"),
    path("trunks/providers/<slug:slug>/delete/", views.provider_delete, name="provider-delete"),
    path("trunks/new/", views.trunk_create, name="trunk-create"),
    path("trunks/<int:trunk_id>/edit/", views.trunk_update, name="trunk-edit"),
    path("trunks/<int:trunk_id>/delete/", views.trunk_delete, name="trunk-delete"),
    path("dial-plan/", views.outbound_route_list, name="dial-plan"),
    path("dial-plan/outbound/new/", views.outbound_route_create, name="outbound-route-create"),
    path("dial-plan/outbound/<int:route_id>/edit/", views.outbound_route_update, name="outbound-route-edit"),
    path("dial-plan/outbound/<int:route_id>/delete/", views.outbound_route_delete, name="outbound-route-delete"),
    path("settings/", views.portal_area, {"slug": "settings"}, name="settings"),
    path("health/", views.health, name="health"),
    path("api/admin/roles/", views.admin_roles, name="admin-roles"),
    path("api/admin/users/", views.admin_users, name="admin-users"),
    path("api/admin/users/<int:user_id>/", views.admin_user_detail, name="admin-user-detail"),
    path("api/admin/service-identities/", views.admin_service_identities, name="service-identity-list"),
    path(
        "api/admin/service-identities/<int:service_identity_id>/",
        views.admin_service_identity_detail,
        name="service-identity-detail",
    ),
    path("api/admin/api-keys/", views.admin_api_keys, name="api-key-create"),
    path("api/admin/api-keys/<int:api_key_id>/rotate/", views.admin_api_key_rotate, name="api-key-rotate"),
    path("api/admin/api-keys/<int:api_key_id>/revoke/", views.admin_api_key_revoke, name="api-key-revoke"),
]
