from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/panel/", views.dashboard_panel, name="dashboard-panel"),
    path("locations/", views.location_list, name="locations"),
    path("locations/new/", views.location_create, name="location-create"),
    path("locations/<slug:slug>/", views.location_detail, name="location-detail"),
    path("locations/<slug:slug>/edit/", views.location_update, name="location-edit"),
    path("locations/<slug:slug>/delete/", views.location_delete, name="location-delete"),
    path("locations/<slug:slug>/exports/", views.location_config_export, name="location-config-export"),
    path(
        "locations/<slug:slug>/exports/<int:version_number>/download/",
        views.location_config_export_download,
        name="location-config-export-download",
    ),
    path(
        "locations/<slug:slug>/exports/<int:version_number>/deploy/",
        views.location_config_export_deploy,
        name="location-config-export-deploy",
    ),
    path(
        "locations/<slug:slug>/exports/<int:version_number>/rollback/",
        views.location_config_export_rollback,
        name="location-config-export-rollback",
    ),
    path("extensions/", views.extension_list, name="extensions"),
    path("extensions/new/", views.extension_create, name="extension-create"),
    path("extensions/import/", views.extension_import, name="extension-import"),
    path("extensions/export/", views.extension_export, name="extension-export"),
    path("extensions/template/", views.extension_template, name="extension-template"),
    path("extensions/<str:number>/edit/", views.extension_update, name="extension-edit"),
    path("extensions/<str:number>/delete/", views.extension_delete, name="extension-delete"),
    path("inbound-destinations/", views.inbound_destination_list, name="inbound-destinations"),
    path("inbound-destinations/new/", views.inbound_destination_create, name="inbound-destination-create"),
    path(
        "inbound-destinations/<int:destination_id>/edit/",
        views.inbound_destination_update,
        name="inbound-destination-edit",
    ),
    path(
        "inbound-destinations/<int:destination_id>/delete/",
        views.inbound_destination_delete,
        name="inbound-destination-delete",
    ),
    path("dids/", views.did_list, name="dids"),
    path("dids/new/", views.did_create, name="did-create"),
    path("dids/<int:did_id>/edit/", views.did_update, name="did-edit"),
    path("dids/<int:did_id>/delete/", views.did_delete, name="did-delete"),
    path("ivrs/", views.ivr_list, name="ivrs"),
    path("ivrs/new/", views.ivr_create, name="ivr-create"),
    path("ivrs/<int:ivr_id>/edit/", views.ivr_update, name="ivr-edit"),
    path("ivrs/<int:ivr_id>/delete/", views.ivr_delete, name="ivr-delete"),
    path("ring-groups/", views.ring_group_list, name="ring-groups"),
    path("ring-groups/new/", views.ring_group_create, name="ring-group-create"),
    path("ring-groups/<int:ring_group_id>/edit/", views.ring_group_update, name="ring-group-edit"),
    path("ring-groups/<int:ring_group_id>/delete/", views.ring_group_delete, name="ring-group-delete"),
    path("queues/", views.queue_list, name="queues"),
    path("queues/new/", views.queue_create, name="queue-create"),
    path("queues/<int:queue_id>/edit/", views.queue_update, name="queue-edit"),
    path("queues/<int:queue_id>/delete/", views.queue_delete, name="queue-delete"),
    path("paging-groups/", views.paging_group_list, name="paging-groups"),
    path("paging-groups/new/", views.paging_group_create, name="paging-group-create"),
    path("paging-groups/<int:paging_group_id>/edit/", views.paging_group_update, name="paging-group-edit"),
    path("paging-groups/<int:paging_group_id>/delete/", views.paging_group_delete, name="paging-group-delete"),
    path("feature-codes/", views.feature_code_list, name="feature-codes"),
    path("feature-codes/new/", views.feature_code_create, name="feature-code-create"),
    path("feature-codes/<int:feature_code_id>/edit/", views.feature_code_update, name="feature-code-edit"),
    path("feature-codes/<int:feature_code_id>/delete/", views.feature_code_delete, name="feature-code-delete"),
    path("phones/", views.phone_list, name="phones"),
    path("phones/new/", views.phone_create, name="phone-create"),
    path("phones/export/", views.phone_export, name="phone-export"),
    path("phones/template/", views.phone_template, name="phone-template"),
    path("phones/dids-template/", views.did_template, name="did-template"),
    path("phones/speed-dials/export/", views.speed_dial_export, name="speed-dial-export"),
    path("phones/speed-dials/template/", views.speed_dial_template, name="speed-dial-template"),
    path("phones/<str:mac_address>/edit/", views.phone_update, name="phone-edit"),
    path("phones/<str:mac_address>/delete/", views.phone_delete, name="phone-delete"),
    path("trunks/", views.trunk_list, name="trunks"),
    path("trunks/providers/new/", views.provider_create, name="provider-create"),
    path("trunks/providers/<slug:slug>/edit/", views.provider_update, name="provider-edit"),
    path("trunks/providers/<slug:slug>/delete/", views.provider_delete, name="provider-delete"),
    path("trunks/new/", views.trunk_create, name="trunk-create"),
    path("trunks/<int:trunk_id>/edit/", views.trunk_update, name="trunk-edit"),
    path("trunks/<int:trunk_id>/delete/", views.trunk_delete, name="trunk-delete"),
    path("dial-plan/", views.outbound_route_list, name="dial-plan"),
    path("dial-plan/outbound/new/", views.outbound_route_create, name="outbound-route-create"),
    path("dial-plan/outbound/<int:route_id>/edit/", views.outbound_route_update, name="outbound-route-edit"),
    path("dial-plan/outbound/<int:route_id>/delete/", views.outbound_route_delete, name="outbound-route-delete"),
    path("settings/", views.settings, name="settings"),
    path("settings/backups/", views.admin_backup_create, name="admin-backup-create"),
    path("settings/backups/<int:backup_id>/download/", views.admin_backup_download, name="admin-backup-download"),
    path("health/", views.health, name="health"),
    path("api/admin/roles/", views.admin_roles, name="admin-roles"),
    path("api/admin/users/", views.admin_users, name="admin-users"),
    path("api/admin/users/<int:user_id>/", views.admin_user_detail, name="admin-user-detail"),
    path("api/admin/service-identities/", views.admin_service_identities, name="service-identity-list"),
    path(
        "api/admin/service-identities/<int:service_identity_id>/",
        views.admin_service_identity_detail,
        name="service-identity-detail",
    ),
    path("api/admin/api-keys/", views.admin_api_keys, name="api-key-create"),
    path("api/admin/api-keys/<int:api_key_id>/rotate/", views.admin_api_key_rotate, name="api-key-rotate"),
    path("api/admin/api-keys/<int:api_key_id>/revoke/", views.admin_api_key_revoke, name="api-key-revoke"),
]
